server:
  port: 8085
spring:
  #  debug: false
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/foodOrderSystem
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      temp:
      user_jdbc_metdata_defaults: false
      use_jdbc_metadata_defaults: false
